//Login
POST http://localhost:3000/users
Content-Type: application/json
Charset:utf-8

{
    "username":"test",
    "password":"test1234"
}

###
//projects
GET http://localhost:3000/projects/?enabled=true&archived=false
Authorization: Bearer 123456
userId:784asdf54a4s4asd2

###
//pageable
GET http://localhost:3000/projects/?page=0&size=3
Authorization: Basic base64-user-password